routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Services\SafecrowService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

//Route::group(['as'=>'oauth.','prefix'=>'oauth'],function(){
//  Route::get('/login','Auth\OAuthController@login')->name('login');
//  Route::get('/callback','Auth\OAuthController@callback')->name('callback');
//  Route::get('/user','Auth\OAuthController@getUser')->name('user');
//});
//
//Auth::routes();
//Route::get('logout', 'Auth\LoginController@logout')->name('logout.link');
//
//Route::get('orders/personal', 'OrderController@personal')->name('orders.personal');
//Route::get('orders', 'OrderController@index')->name('orders.index');
//
//Route::get('orders/{order}/decline', 'OrderController@decline')->name('orders.decline');
//Route::get('orders/{order}/done', 'OrderController@done')->name('orders.done');
//Route::get('orders/{order}/resume', 'OrderController@resume')->name('orders.resume');
//Route::get('orders/{order}/argue', 'OrderController@argue')->name('orders.argue');
//
//Route::resource('orders', 'OrderController')->only(['index', 'show', 'create', 'store']);
//Route::post('responds/{respond}/comment', 'RespondController@comment')->name('responds.comment');
//Route::post('responds', 'RespondController@store')->name('responds.store')->middleware(['auth']);
//Route::post('responds/{respond}/choose', 'RespondController@choose')->name('responds.choose');
//Route::post('complaint', 'ComplaintController@store')->name('complaint.store')->middleware(['auth']);
//
//Route::resource('users', 'UserController')->only(['show']);
//Route::get('profile', 'UserController@profile')->name('users.profile')->middleware(['auth']);
//Route::post('profile', 'UserController@update')->name('profile.update')->middleware(['auth']);
//Route::put('profile', 'UserController@setType')->name('users.profile.set')->middleware((['auth']));
//
//
//// STATIC PAGES
//
//Route::get('about', 'StaticController@about')->name('about');
//Route::get('ru1es', 'StaticController@rules')->name('rules');
//Route::get('faq', 'StaticController@faq')->name('faq');
//
//// Layout
//
//Route::get('/', function () {
//    return view('index');
//});

Route::middleware('auth')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@setType')->name('users.profile.set');
    Route::post('profile', 'UserController@update')->name('profile.update');
    Route::post('profile/pw', 'UserController@updatepw')->name('users.updatepw');
    Route::post('profile/photo', 'UserController@uploadPhoto')->name('profile.upload');

    Route::get('orders/create', 'OrderController@create')->name('orders.create');
    Route::post('orders', 'OrderController@store')->name('orders.store');
    Route::get('orders/{order}/done', 'OrderController@done')->name('orders.done');
    Route::get('orders/{order}/resume', 'OrderController@resume')->name('orders.resume');
    Route::get('orders/{order}/argue', 'OrderController@argue')->name('orders.argue');
    Route::get('orders/{order}/update', 'OrderController@updateStatus')->name('orders.updateStatus');
    Route::post('complaint', 'ComplaintController@store')->name('complaint.store');
    Route::get('orders/{order}/decline', 'OrderController@decline')->name('orders.decline');
    Route::get('orders/{order}/close', 'OrderController@close')->name('orders.close');
    Route::get('orders/{order}/renew', 'OrderController@guarantee')->name('orders.renew');

    Route::post('responds', 'RespondController@store')->name('responds.store')->middleware('sccard');
    Route::post('responds/{respond}/choose', 'RespondController@choose')->name('responds.choose');
    Route::post('responds/{id}/updatecost', 'RespondController@updateCost')->name('responds.setcost');
    Route::post('responds/{id}/accept', 'RespondController@accept')->name('responds.accept');
    Route::get('responds/{id}/reject', 'RespondController@discard')->name('responds.reject');

    Route::post('alert/{notification}', 'NotificationController@read')->name('notifications.read');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout.get');
});

Route::get('/', 'HomeController@index')->name('index');

Route::get('/about', 'StaticController@about')->name('about');
Route::get('/rules', 'StaticController@rules')->name('rules');
Route::get('/faq', 'StaticController@faq')->name('faq');
Route::get('/privacy-policy', 'StaticController@privacyPolicy')->name('privacy-policy');
Route::get('/user-agreement', 'StaticController@userAgreement')->name('user-agreement');

Route::prefix('faq')->group(function () {
    Route::get('pin', 'StaticController@pin')->name('faq.pin');
    Route::get('money-out', 'StaticController@moneyOut')->name('faq.money-out');
    Route::get('account', 'StaticController@account')->name('faq.account');
    Route::get('cost', 'StaticController@cost')->name('faq.cost');
    Route::get('what', 'StaticController@what')->name('faq.what');
    Route::get('freese', 'StaticController@freese')->name('faq.freese');
    Route::get('fee', 'StaticController@fee')->name('faq.fee');
    Route::get('payment', 'StaticController@payment')->name('faq.payment');
});

Route::get('orders', 'OrderController@index')->name('orders');
Route::get('orders/personal', 'OrderController@personal')->name('orders.personal');
Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
Route::get('users/{user}', 'UserController@show')->name('users.show');

Route::post('responds/{respond}/comment', 'RespondController@comment')->name('responds.comment');
Route::post('/users/{id}/safecrow', 'UserController@createSafecrowProfile')->name('users.safecrowprofile');

Auth::routes();
Route::group(['as'=>'oauth.','prefix'=>'oauth'],function(){
  Route::get('/login','Auth\OAuthController@login')->name('login');
  Route::get('/callback','Auth\OAuthController@callback')->name('callback');
  Route::get('/user','Auth\OAuthController@getUser')->name('user');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('/orders/{id}/complaintread', 'AdminController@readComplaints')->name('markRead');
    Route::get('/orders/{order}/ban', 'OrderController@ban')->name('orders.ban');
});

app/User.php
<?php

namespace App;

use App\Services\SafecrowService;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;
use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{
    const TYPE_CUSTOMER = 'customer';
    const TYPE_EXECUTANT = 'executant';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'email',
        'password',
        'roles_id',
        'permissions',
        'profile_type',
        'type',
        'sc_user_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    public static function boot()
    {
        parent::boot();

        static::addGlobalScope('isBanned', function ($builder) {
            $builder->where('is_banned', false);
        });
    }

    public function site_roles()
    {
        return $this->belongsTo(Role::class, 'roles_id');
    }

    public function executant_profile()
    {
        return $this->belongsTo(ExecutantProfile::class, 'executant_profile_id');
    }

    public function customer_profile()
    {
        return $this->belongsTo(CustomerProfile::class, 'customer_profile_id');
    }

    public function avatar()
    {
        return $this->belongsTo(File::class, 'avatar_file_id');
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Отображает оценки, которые проставил пользователь
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rated()
    {
        return $this->hasMany(Rating::class, 'user_id');
    }

    /**
     * Отображает только оценки, которые получил пользователь
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ratings()
    {
        return $this->hasMany(Rating::class, 'executant_id');
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'user_id');
    }

    public function complaints()
    {
        return $this->hasMany(Complaint::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id');
    }

    public function responds()
    {
        return $this->hasMany(Respond::class, 'user_id');
    }

    public function social_user()
    {
        return $this->hasMany(SocialUser::class, 'user_id', 'id');
    }

    public function getAuthIdentifierName()
    {
        return 'email';
    }

    public function getAvatarUrlAttribute()
    {
        return $this->avatar ? Storage::url($this->avatar->path) : '/storage/img/avatar.png';
    }

    public function customerValidationParameters()
    {
        return [
            'username' => 'required|string|max:191',
        ];
    }

    public function executantValidationParameters()
    {
        return [
            'username' => 'required|string|max:191',
            'qualification' => 'required|string|max:191',
            'about' => 'required|string|nullable',
            'education' => 'required|string',
            'academic_title_id' => 'required|exists:academic_titles,id',
            'academic_degree_id' => 'required|exists:academic_degrees,id'
        ];
    }

    /**
     * @return array
     * @throws \Exception
     */
    public function getValidationParameters()
    {
        if ($this->type == self::TYPE_CUSTOMER) {
            return $this->customerValidationParameters();
        } else {
            if ($this->type == self::TYPE_EXECUTANT) {
                return $this->executantValidationParameters();
            }
        }

        throw new \Exception("User must be either customer or executant");
    }

    public function addedRespond($orderId)
    {
        return $this->responds()->where('order_id', $orderId)->count() > 0;
    }

    public function personalOrder($orderId)
    {
        $order = Order::findOrFail($orderId);
        if (($order->winner && $order->winner->user->id == $this->id) || $order->user->id == $this->id) {
            return true;
        }
        return false;
    }

    public function personalOrders()
    {
        return Order::where('user_id', auth()->user()->id)->orWhereHas('winner', function($q){
            $q->where('user_id', auth()->user()->id);
        })->get();
    }

    public function averageRatings()
    {
        return round($this->ratings()->average('score'), 0);
    }

    public function anyUnreadNotification()
    {
        return $this->notifications()->where('read_at', null)->count() > 0;
    }

    public function hasUnvalidatedAlert()
    {
        return true;
    }

    public function hasSafecrowAccount()
    {
        return $this->sc_user_id ? true : false;
    }

    public function hasAssignedCard()
    {
        $safecrow = new SafecrowService();
        return $safecrow->hasAssignedCard($this->sc_user_id);
    }

    public function getCardAssignUrl()
    {
        $safecrow = new SafecrowService();
        $safecrowCardLink = $safecrow->getCardUrl(auth()->user()->sc_user_id, ['redirect_url' => URL::current()]);
        return $safecrowCardLink;
    }

    public function getListOfUserCards()
    {
        $safecrow = new SafecrowService();
        $safecrowCardList = $safecrow->attachedCards(auth()->user()->sc_user_id);
        return $safecrowCardList;
    }

    public function getListOfUserCardIds($cards)
    {
        $list = [];
        foreach ($cards as $item) {
            $list[] = $item->id;
        }

        return $list;
    }

    //TODO Move this to somewhere illogical
    public function getPaymentUrl(Order $order)
    {
        $sc = new SafecrowService();
        return $sc->getPaymentUrl($order->sc_order_id, $order->id);
    }

}

resources/views/admin/parts/order-complaints.blade.php
<div class="card mt-5">
    <div class="card-header d-flex justify-content-between">
        <div class="card__title card__title_small">
            Список жалоб
        </div>
        <a class="text-green" href="{{ route('admin.markRead', ['id' => $order->id]) }}">
            <i class="fa fa-eye"></i>
        </a>
    </div>
    <div class="card-body">
        @foreach($complaints as $key => $complaint)
            <div class="complaint d-flex border-bottom pb-4 {{ $key == 0 ? '' : 'pt-4' }}">
                @if($complaint->user)
                <div class="submitter">
                    <span class="avatar" style="background-image: url('{{ asset($complaint->user->avatar_url) }}')"></span>
                </div>
                @endif
                <div class="text text-muted ml-3">
                    {{ $complaint->comment }}
                </div>
            </div>
        @endforeach
    </div>
</div>

resources/views/admin/parts/order.blade.php
<div class="card__subcard">
    <div class="d-flex align-items-center">
        <div class="info__element col p-0 text-muted mr-2">
            <i class="fa fa-clock-o mr-1"></i>
            {{ $order->created_at->format('Y-m-d H:i') }}
        </div>
        <div class="info__element col p-0 text-muted mr-2">
            <i class="fa fa-calendar-o mr-1"></i>
            до {{ $order->deadline->format('Y-m-d H:i') }}
        </div>
        <div class="info__element col p-0 text-muted mr-2">
            <span class="fa-icon mr-1">ID</span>
            {{ $order->id }}
        </div>
        <div class="info__element text-red mr-4 p-0">
            <i class="fa fa-legal"></i>
            {{ $order->complaints->count() }}
        </div>
        <div class="cost">
            {{ $order->budget }}
        </div>
    </div>

    <div class="order__info">
        <div class="order__title">
            <a href="{{ route('orders.show', ['id' => $order->id]) }}">{{ $order->title }}</a>
        </div>
        <div class="order__categories order__categories_long">
            @foreach($order->subjects as $subject)
                <span>{{ $subject->name }}</span>
            @endforeach
        </div>
    </div>

    <div class="form__divider form__divider_dark mt-4 cursor-pointer js-hidden-open">
        <span>Подробнее <i class="fa fa-chevron-down"></i></span>
    </div>

    <div class="hidden__info">
        <div class="subcard__info mt-3">
            <div class="col-lg-4 d-flex flex-column p-0">
                <div class="text-default mb-4">
                    Заказчик
                </div>
                <div class="d-flex align-items-center">
                    <div class="response__image mr-3">
                        <span class="avatar" style="background-image: url('{{ $order->user->avatar_url }}')"></span>
                    </div>
                    <div class="response__profile-info">
                        <div class="profile-info__name">{{ $order->user->username }}</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 d-flex flex-column p-0">
                <div class="text-default mb-4">
                    Информация о заказе
                </div>
                <div>
                    <div class="response__commentary">
                        <p>{{ $order->description }}</p>
                    </div>
                    <div class="subcard__info mt-3">
                        <div class="d-flex mr-3">
                            <div class="point-icon mr-2">
                                <img src="/img/pages.svg" alt="">
                            </div>
                            <div class="point-description">
                                {{ $order->work_amount }} страниц
                            </div>
                        </div>
                        <div class="response__documents">
                            @foreach($order->files as $file)
                                <div>
                                    <span class="document__icon">
                                        <img src="/img/file.svg" alt=""></span>
                                    <a download href="{{ Storage::url($file->path) }}" class="document__name">{{ $file->original_name }}</a>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>