routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Services\SafecrowService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

//Route::group(['as'=>'oauth.','prefix'=>'oauth'],function(){
//  Route::get('/login','Auth\OAuthController@login')->name('login');
//  Route::get('/callback','Auth\OAuthController@callback')->name('callback');
//  Route::get('/user','Auth\OAuthController@getUser')->name('user');
//});
//
//Auth::routes();
//Route::get('logout', 'Auth\LoginController@logout')->name('logout.link');
//
//Route::get('orders/personal', 'OrderController@personal')->name('orders.personal');
//Route::get('orders', 'OrderController@index')->name('orders.index');
//
//Route::get('orders/{order}/decline', 'OrderController@decline')->name('orders.decline');
//Route::get('orders/{order}/done', 'OrderController@done')->name('orders.done');
//Route::get('orders/{order}/resume', 'OrderController@resume')->name('orders.resume');
//Route::get('orders/{order}/argue', 'OrderController@argue')->name('orders.argue');
//
//Route::resource('orders', 'OrderController')->only(['index', 'show', 'create', 'store']);
//Route::post('responds/{respond}/comment', 'RespondController@comment')->name('responds.comment');
//Route::post('responds', 'RespondController@store')->name('responds.store')->middleware(['auth']);
//Route::post('responds/{respond}/choose', 'RespondController@choose')->name('responds.choose');
//Route::post('complaint', 'ComplaintController@store')->name('complaint.store')->middleware(['auth']);
//
//Route::resource('users', 'UserController')->only(['show']);
//Route::get('profile', 'UserController@profile')->name('users.profile')->middleware(['auth']);
//Route::post('profile', 'UserController@update')->name('profile.update')->middleware(['auth']);
//Route::put('profile', 'UserController@setType')->name('users.profile.set')->middleware((['auth']));
//
//
//// STATIC PAGES
//
//Route::get('about', 'StaticController@about')->name('about');
//Route::get('ru1es', 'StaticController@rules')->name('rules');
//Route::get('faq', 'StaticController@faq')->name('faq');
//
//// Layout
//
//Route::get('/', function () {
//    return view('index');
//});

Route::middleware('auth')->group(function () {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@setType')->name('users.profile.set');
    Route::post('profile', 'UserController@update')->name('profile.update');
    Route::post('profile/pw', 'UserController@updatepw')->name('users.updatepw');
    Route::post('profile/photo', 'UserController@uploadPhoto')->name('profile.upload');

    Route::get('orders/create', 'OrderController@create')->name('orders.create');
    Route::post('orders', 'OrderController@store')->name('orders.store');
    Route::get('orders/{order}/done', 'OrderController@done')->name('orders.done');
    Route::get('orders/{order}/resume', 'OrderController@resume')->name('orders.resume');
    Route::get('orders/{order}/argue', 'OrderController@argue')->name('orders.argue');
    Route::get('orders/{order}/update', 'OrderController@updateStatus')->name('orders.updateStatus');
    Route::post('complaint', 'ComplaintController@store')->name('complaint.store');
    Route::get('orders/{order}/decline', 'OrderController@decline')->name('orders.decline');
    Route::get('orders/{order}/close', 'OrderController@close')->name('orders.close');
    Route::get('orders/{order}/renew', 'OrderController@guarantee')->name('orders.renew');

    Route::post('responds', 'RespondController@store')->name('responds.store')->middleware('sccard');
    Route::post('responds/{respond}/choose', 'RespondController@choose')->name('responds.choose');
    Route::post('responds/{id}/updatecost', 'RespondController@updateCost')->name('responds.setcost');
    Route::post('responds/{id}/accept', 'RespondController@accept')->name('responds.accept');
    Route::get('responds/{id}/reject', 'RespondController@discard')->name('responds.reject');

    Route::post('alert/{notification}', 'NotificationController@read')->name('notifications.read');

    Route::get('logout', 'Auth\LoginController@logout')->name('logout.get');
});

Route::get('/', 'HomeController@index')->name('index');

Route::get('/about', 'StaticController@about')->name('about');
Route::get('/rules', 'StaticController@rules')->name('rules');
Route::get('/faq', 'StaticController@faq')->name('faq');
Route::get('/privacy-policy', 'StaticController@privacyPolicy')->name('privacy-policy');
Route::get('/user-agreement', 'StaticController@userAgreement')->name('user-agreement');

Route::prefix('faq')->group(function () {
    Route::get('pin', 'StaticController@pin')->name('faq.pin');
    Route::get('money-out', 'StaticController@moneyOut')->name('faq.money-out');
    Route::get('account', 'StaticController@account')->name('faq.account');
    Route::get('cost', 'StaticController@cost')->name('faq.cost');
    Route::get('what', 'StaticController@what')->name('faq.what');
    Route::get('freese', 'StaticController@freese')->name('faq.freese');
    Route::get('fee', 'StaticController@fee')->name('faq.fee');
    Route::get('payment', 'StaticController@payment')->name('faq.payment');
});

Route::get('orders', 'OrderController@index')->name('orders');
Route::get('orders/personal', 'OrderController@personal')->name('orders.personal');
Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
Route::get('users/{user}', 'UserController@show')->name('users.show');

Route::post('responds/{respond}/comment', 'RespondController@comment')->name('responds.comment');
Route::post('/users/{id}/safecrow', 'UserController@createSafecrowProfile')->name('users.safecrowprofile');

Auth::routes();
Route::group(['as'=>'oauth.','prefix'=>'oauth'],function(){
  Route::get('/login','Auth\OAuthController@login')->name('login');
  Route::get('/callback','Auth\OAuthController@callback')->name('callback');
  Route::get('/user','Auth\OAuthController@getUser')->name('user');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('/orders/{id}/complaintread', 'AdminController@readComplaints')->name('markRead');
    Route::get('/orders/{order}/ban', 'OrderController@ban')->name('orders.ban');
});

app/User.php
<?php

namespace App;

use App\Services\SafecrowService;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;
use Orchid\Platform\Core\Models\User as BaseUser;

class User extends BaseUser
{
    const TYPE_CUSTOMER = 'customer';
    const TYPE_EXECUTANT = 'executant';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'email',
        'password',
        'roles_id',
        'permissions',
        'profile_type',
        'type',
        'sc_user_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    public static function boot()
    {
        parent::boot();

        static::addGlobalScope('isBanned', function ($builder) {
            $builder->where('is_banned', false);
        });
    }

    public function site_roles()
    {
        return $this->belongsTo(Role::class, 'roles_id');
    }

    public function executant_profile()
    {
        return $this->belongsTo(ExecutantProfile::class, 'executant_profile_id');
    }

    public function customer_profile()
    {
        return $this->belongsTo(CustomerProfile::class, 'customer_profile_id');
    }

    public function avatar()
    {
        return $this->belongsTo(File::class, 'avatar_file_id');
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Отображает оценки, которые проставил пользователь
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rated()
    {
        return $this->hasMany(Rating::class, 'user_id');
    }

    /**
     * Отображает только оценки, которые получил пользователь
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ratings()
    {
        return $this->hasMany(Rating::class, 'executant_id');
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'user_id');
    }

    public function complaints()
    {
        return $this->hasMany(Complaint::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id');
    }

    public function responds()
    {
        return $this->hasMany(Respond::class, 'user_id');
    }

    public function social_user()
    {
        return $this->hasMany(SocialUser::class, 'user_id', 'id');
    }

    public function getAuthIdentifierName()
    {
        return 'email';
    }

    public function getAvatarUrlAttribute()
    {
        return $this->avatar ? Storage::url($this->avatar->path) : '/storage/img/avatar.png';
    }

    public function customerValidationParameters()
    {
        return [
            'username' => 'required|string|max:191',
        ];
    }

    public function executantValidationParameters()
    {
        return [
            'username' => 'required|string|max:191',
            'qualification' => 'required|string|max:191',
            'about' => 'required|string|nullable',
            'education' => 'required|string',
            'academic_title_id' => 'required|exists:academic_titles,id',
            'academic_degree_id' => 'required|exists:academic_degrees,id'
        ];
    }

    /**
     * @return array
     * @throws \Exception
     */
    public function getValidationParameters()
    {
        if ($this->type == self::TYPE_CUSTOMER) {
            return $this->customerValidationParameters();
        } else {
            if ($this->type == self::TYPE_EXECUTANT) {
                return $this->executantValidationParameters();
            }
        }

        throw new \Exception("User must be either customer or executant");
    }

    public function addedRespond($orderId)
    {
        return $this->responds()->where('order_id', $orderId)->count() > 0;
    }

    public function personalOrder($orderId)
    {
        $order = Order::findOrFail($orderId);
        if (($order->winner && $order->winner->user->id == $this->id) || $order->user->id == $this->id) {
            return true;
        }
        return false;
    }

    public function personalOrders()
    {
        return Order::where('user_id', auth()->user()->id)->orWhereHas('winner', function($q){
            $q->where('user_id', auth()->user()->id);
        })->get();
    }

    public function averageRatings()
    {
        return round($this->ratings()->average('score'), 0);
    }

    public function anyUnreadNotification()
    {
        return $this->notifications()->where('read_at', null)->count() > 0;
    }

    public function hasUnvalidatedAlert()
    {
        return true;
    }

    public function hasSafecrowAccount()
    {
        return $this->sc_user_id ? true : false;
    }

    public function hasAssignedCard()
    {
        $safecrow = new SafecrowService();
        return $safecrow->hasAssignedCard($this->sc_user_id);
    }

    public function getCardAssignUrl()
    {
        $safecrow = new SafecrowService();
        $safecrowCardLink = $safecrow->getCardUrl(auth()->user()->sc_user_id, ['redirect_url' => URL::current()]);
        return $safecrowCardLink;
    }

    public function getListOfUserCards()
    {
        $safecrow = new SafecrowService();
        $safecrowCardList = $safecrow->attachedCards(auth()->user()->sc_user_id);
        return $safecrowCardList;
    }

    public function getListOfUserCardIds($cards)
    {
        $list = [];
        foreach ($cards as $item) {
            $list[] = $item->id;
        }

        return $list;
    }

    //TODO Move this to somewhere illogical
    public function getPaymentUrl(Order $order)
    {
        $sc = new SafecrowService();
        return $sc->getPaymentUrl($order->sc_order_id, $order->id);
    }

}

resources/views/parts/breadcrumbs.blade.php
<div class="page__title-container">
    <h2 class="page-title">{{ $title }}</h2>
    <div class="breadcrumps">
        <ul class="breadcrump__list">
            @foreach($breadcrumbs as $breadcrumb)
                <li class="breadcrump__item">
                    <a href="{{ $breadcrumb['link']}}" class="breadcrump__link">{{ $breadcrumb['name'] }}</a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/parts/footer.blade.php
<footer class="page__footer">
    <div class="container">
        <div class="row justify-content-between mr-0 ml-0">
            <div class="footer__description-block">
                <h4 class="footer__title">Эксперт<span class="footer__title_blue">24</span></h4>
                <p class="footer__description">Проект Эксперт24 ‒ это интернет-сервис для помощи и консультации по любым видам учебных работ. Сотни квалифицированных специалистов практически по всем предметам готовы уже сейчас приступить к Вашему заказ</p>
            </div>
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="{{ route('about') }}" class="footer__link">О проекте</a></li>
                    <li class="footer__list-item"><a href="{{ route('rules') }}" class="footer__link">Правила работы</a></li>
                    <li class="footer__list-item"><a href="{{ route('faq') }}" class="footer__link">Часто задаваемые вопросы</a></li>
                    <li class="footer__list-item"><a href="{{ route('user-agreement') }}" class="footer__link">Пользовательское соглашение</a></li>
                    <li class="footer__list-item"><a href="{{ route('privacy-policy') }}" class="footer__link">Политика конфиденциальности</a></li>
                </ul>
            </nav>
            <div class="footer__social">
                <h5 class="socials__title">Мы в социальных сетях</h5>
                <div class="d-flex">
                    <a href="https://vk.com/public172422913" class="social__link social__link_vk"><i class="fa fa-vk"></i></a>
                    <a href="https://www.facebook.com/groups/2168209820117095/" class="social__link social__link_fb"><i class="fa fa-facebook"></i></a>
                    <a href="https://ok.ru/group/54006645981320" class="social__link social__link_ig"><img src="{{ asset('img/ok.svg') }}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</footer>
<footer class="page__last-footer background-white">
    <div class="container">
        <div class="row justify-content-between align-items-center mr-0 ml-0">
            <div class="footer__accept d-none d-sm-flex">
                <div class="accept__item"><img src="{{asset('img/visa.svg')}}" alt=""></div>
                <div class="accept__item"><img src="{{asset('img/mastercard.svg')}}" alt=""></div>
            </div>
            <div class="footer__copyright">"Эксперт24" - &copy; Все права защищены</div>
            
        </div>
    </div>
    
</footer>

resources/views/parts/header.blade.php
<header class="header border-bottom bg-white p-5">
    <div class="container">
        <div class="d-flex align-items-center justify-content-between">
            <div class="m-0 p-0">
                <a href="{{ route('index') }}">
                    <img src="{{ asset('img/logo.svg') }}" alt="" class="logo logo_header">
                </a>
            </div>
            <div class="d-none d-xl-block m-0 p-0">
                @include('layouts.parts.menu')
            </div>
            <div class="d-flex justify-content-end m-0 p-0">
                @if(!auth()->check())
                    <div class="login">
                        <a href="#" class="btn btn-outline-primary" data-target="#authorizationModal"
                           data-toggle="modal">Войти</a>
                    </div>
                @else
                    <div class="dropdown">
                        <a href="#" class="nav-link icon h-100 pr-5" data-toggle="dropdown">
                            <div>
                                <i class="fa fa-bell-o"></i>
                            </div>

                            @if(auth()->user()->anyUnreadNotification())
                                <span class="nav-unread"></span>
                            @endif
                        </a>
                        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                            @foreach(auth()->user()->unreadNotifications as $notification)
                                <div class="dropdown-item d-flex">
                                    @if($notification->link )
                                        <a href="{{ $notification->link }}">
                                            {!! $notification->text !!}
                                        </a>
                                    @else
                                        <div>
                                            {!! $notification->text !!}
                                        </div>
                                    @endif
                                    <small>
                                        <form class="d-flex align-items-center"
                                              action="{{ route('notifications.read', ['id' => $notification->id])  }}"
                                              method="POST">
                                            @csrf
                                            <button class="btn btn-sm text-success btn-none"><i class="fa fa-check"></i>
                                            </button>
                                        </form>
                                    </small>
                                </div>
                            @endforeach
                            @if (!auth()->user()->anyUnreadNotification())
                                <div class="dropdown-item d-flex">
                                    <span class="text-muted">У вас нет непрочитанных уведомлений</span>
                                </div>
                            @endif
                            {{--<div class="dropdown-divider"></div>--}}
                            {{--<a href="#" class="dropdown-item text-muted-dark text-center">Отметить все прочитанными</a>--}}
                        </div>
                    </div>
                    <div class="d-flex dropdown">
                        <a href="#" class="nav-link p-0 d-flex align-items-center flex-row" data-toggle="dropdown">
                            <span class="avatar mr-md-2 mr-none d-block"
                                  style="background-image: url('{{ auth()->user()->avatar_url  }}')"></span>
                            <div class="d-flex flex-column ml-1">
                                <span class="text-default leading-none font-weight-bold d-md-block d-none mb-1">{{ auth()->user()->username }}</span>
                                <span class="text-muted leading-none d-md-block d-none ">
                                    @if(auth()->user()->type == \App\User::TYPE_CUSTOMER)
                                        Заказчик
                                    @elseif(auth()->user()->type == \App\User::TYPE_EXECUTANT)
                                        Исполнитель
                                    @else
                                        <span class="text-danger">Создайте профиль</span>
                                    @endif
                                </span>
                            </div>
                            <i class="fa fa-chevron-down text-muted ml-0 ml-md-3"></i>
                        </a>
                        @if(auth()->check() && auth()->user()->type)
                            @if(auth()->user()->type == \App\User::TYPE_CUSTOMER)
                                <a href="{{ route('orders.create') }}"
                                   class="btn btn-outline-primary ml-5 d-lg-block d-none">Создать заказ</a>
                            @else
                                <a href="{{ route('orders') }}" class="btn btn-outline-primary ml-5 d-lg-block d-none">Искать
                                    заказ</a>
                            @endif
                        @endif
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="{{ route('profile') }}" class="dropdown-item"><i
                                        class="fa fa-user dropdown-icon"></i> Профиль</a>
                            @if(auth()->check())
                                @can('admin')
                                    <a href="{{ route('admin.index') }}" class="dropdown-item">
                                        <i class="fa fa-pie-chart dropdown-icon"></i> Админка</a>
                                @endcan
                            @endif
                            @if(auth()->check() && auth()->user()->type)
                                <a href="{{ route('orders.personal') }}" class="dropdown-item"><i
                                            class="fa fa-tasks dropdown-icon"></i> Мои заказы</a>
                                @if(!auth()->user()->type == \App\User::TYPE_CUSTOMER || auth()->user()->can('admin'))
                                    <a href="{{ route('orders') }}" class="dropdown-item"><i
                                                class="fa fa-balance-scale dropdown-icon"></i> Биржа заказов</a>
                                @endif
                            @endif
                            <a href="{{ route('logout.get') }}" class="dropdown-item"><i
                                        class="fa fa-sign-out dropdown-icon"></i> Выход</a>
                        </div>
                    </div>
                @endif

                <a href="#" class="header-toggler d-xl-none ml-3 ml-xl-0" data-toggle="collapse"
                   data-target="#collapsableHeader">
                    <span class="header-toggler-icon"></span>
                </a>
            </div>
        </div>
    </div>
</header>

<!-- Togglable Navigation -->
@include('layouts.parts.togglableNav')
<!-- End of togglable navigation -->